### ISSUE TITLE
[SETTING] Issue, PR Templete 설정

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#1]
## 💡 Issue
이슈 템플릿과 PR 템플릿을 설정합니다.

## 📝  todo
- [x] 기본 이슈 템플릿 추가
- [x] 버그 이슈 템플릿 추가
- [x] PR 템플릿 추가
