### ISSUE TITLE
[BUG] CategoryContentsViewController 레이아웃 오류 수정

### ISSUE THREAD

**Issue by beansbin** [TeamHavit/Havit-iOS#106]
## 💡 Issue
CategoryContentsViewController 검색바 scroll 안되는 오류 , 레이아웃 오류 수정

## 📝  todo
- [x] 정렬 버튼 터치 시 글씨 크기
- [x] 네비게이션바 커스텀
- [x] 처음 진입하면 전체 컬렉션뷰셀 선택되어있도록하기
- [x] 필터셀 클릭된 알람 이미지 변경
