### ISSUE TITLE
[ADD] TableView 세부 디테일 적용 및 EmptyView 생성

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#114]
## 💡 Issue

TableView Separator 삭제 및 alpha 적용
EmptyView 적용

## 📝  todo
- [x] TableView Separator 삭제
- [x] tableview 터치 Selected 수정
- [x] #115
- [x] 카테고리 EmptyView 생성
- [x] 최근 콘텐츠 EmptyView 생성
