### ISSUE TITLE
[FEAT] 전체 Category View에서 화면 전환 및 Data 전달 

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#121]
## 💡 Issue

서버에서 받아온 전체 카테고리 정보들을 전체 카테고리 뷰에서 카테고리 관리뷰로 전달하여 저장합니다.  (VC-> VC) 
카테고리 관리뷰에서 갖고 있는 카테고리 정보들을 셀의 수정 버튼을 누를 때 데이터를 전달 합니다. (Cell -> VC)

## 📝  todo
- [x] 전체 카테고리 뷰에서 카테고리 관리 뷰로 데이터 전달 
- [x] 카테고리 관리 뷰 Cell 에서 개별 카테고리 수정 뷰로 데이터 전달 
- [x] 카테고리 관리 뷰 Cell 에서 받은 개별 카테고리 정보를 수정 뷰 api의 request body로 넘겨줍니다.
