### ISSUE TITLE
[FEAT] 카테고리 추가 플로우 연결 

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#179]
## 💡 Issue

카테고리를 추가하는 플로우를 연결합니다.

## 📝  todo
- [ ] 카테고리 제목 입력 뷰 present 
- [ ] 카테고리 아이콘 선택 뷰
- [ ] 완료 누를 시, dismiss
