### ISSUE TITLE
[FEAT] CategoryContenetsView 뷰 전환 구현

### ISSUE THREAD

**Issue by beansbin** [TeamHavit/Havit-iOS#216]
## 💡 Issue
[FEAT] CategoryContenetsView 뷰 전환 구현

## 📝  todo
- [ ] 제목 수정 화면으로 이동
- [ ] 공유 화면으로 이동
- [ ] 카테고리 받아서 리로드 구현
