### ISSUE TITLE
[FEAT] 메인뷰 기본 Layout 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#22]
## 💡 Issue
메인뷰 기본적인 Layout 구성을 만듭니다.
Cell 내부 이외에 Layout를 구현해둡니다.

## 📝  todo
- [x] 상단 고정뷰 
- [x] TableView -> 셀마다 크기 변경
- [ ] TableView Sticky Header 구현
- [ ] TableView Footer 구현
