### ISSUE TITLE
[FEAT] CategoryContents View 기본 Layout 구성

### ISSUE THREAD

**Issue by beansbin** [TeamHavit/Havit-iOS#24]
## 💡 Issue
카테고리를 클릭했을 때 진입하는 컨텐츠 뷰 UI Design

## 📝  todo
- [x] seach bar 생성
- [x] 필터 뷰 : 컬렉션 뷰 넣기
- [x] 필터 뷰 : 보기 버튼, 정렬 버튼 넣기
- [x] 메인 컨텐츠 뷰 : 컬렉션 뷰 넣기
- [x] 메인 컨텐츠 뷰 : 컬렉션 뷰 셀 만들기(컨텐츠 없음, 정렬1, 정렬2, 정렬3)
- [x] AutoLayouts 설정
