### ISSUE TITLE
[FEAT] CategoryContents View 세부 기능 추가하기

### ISSUE THREAD

**Issue by beansbin** [TeamHavit/Havit-iOS#26]
## 💡 Issue
CategoryContentsView 세부 기능 추가하기

## 📝  todo
- [x] BTNavigationDropDownMenu 라이브러리 설치 및 구현하기
- [x] 네비게이션 바 right item 넣기
- [x] 토스트 메시지 구현하기
- [x] Bottom Panel 구현하기 (정렬, 더보기)
- [x] CategoryContetnsCoordinator 생성
- [x] 정렬 변경 버튼 구현
