### ISSUE TITLE
[FEAT] CategoryContents View UI Design

### ISSUE THREAD

**Issue by beansbin** [TeamHavit/Havit-iOS#27]
## 💡 Issue
CategoryContentsView UI Design

## 📝  todo
- [x] 네비게이션바 커스텀
- [x] 검색바 커스텀
- [x] filterView 버튼들 디자인 적용
- [x] filterCollectionViewCell 디자인 적용
- [x] ContentsCollectionViewCell 디자인 적용
- [x] ContentsCollectionViewCell_sort2 디자인 적용
- [x] ContentsCollectionViewCell_sort3 디자인 적용
- [x] 레이아웃 세부적으로 다시 조정하기
