### ISSUE TITLE
[ADD] URLSession BASE 코드 추가

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#30]
## 💡 Issue
URLSession BASE 코드를 추가합니다.

## 📝  todo
- [x] URLSession Base 추가
- [x] 서버 StatusCode
- [x] APIEnvironment 2개로 설정
- [x] Mock 넣기
- [x] Mock Extension 추가
