### ISSUE TITLE
[ADD] 메인뷰 도달률 Section 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#39]
## 💡 Issue

도달률 관련 Section 셀을 구현합니다.

## 📝  todo
- [x] 도달률 Notification Cell 구현
- [x] 도달률 프로그래스 Cell 구현
- [x] Notification Cell 삭제 로직 구현
