### ISSUE TITLE
[FEAT] ManageCategoryView 기본 레이아웃 구현 및 화면전환

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#42]
## 💡 Issue

CategoryView에서 ManageCategoryView로 화면 전환을 구현하고, ManageCategoryView 의 기본 레이아웃을 구성합니다.

## 📝  todo

- [x] ManageCategoryView Coordinator 추가
- [x] CategoryView에서 ManageCategoryView로 화면전환 구현 
- [x] ManageCategoryView 기본 레이아웃 구성
- [x] ManageCategoryView NaviBar
