### ISSUE TITLE
[FEAT] ManageCategoryView Drag & Drop 순서 변경 기능 구현 

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#55]
## 💡 Issue

ManageCategoryViewController  Drag & Drop 순서 변경 기능 구현 

## 📝  todo
- [ ] LongPress 제스처 추가하기 
- [ ] 제스처 실행 시 press된 셀 색상 변경 및 아이콘 hidden
- [ ] 순서 변경 된  index 반영 후 저장
