### ISSUE TITLE
[SETTING] Coordinator 추가

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#6]
## 💡 Issue
Coordinator를 추가합니다.

## 📝  todo
- [x] Foundation 파일 추가
- [x] Scene 연결 변경
- [x] SceneDelegate에 적용해보기(MainViewController)
