### ISSUE TITLE
[FEAT] EditCategoryView UI 및 레이아웃 구현 

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#64]
## 💡 Issue

개별 카테고리를 수정하는 EditCategoryView 의 UI 및 레이아웃을 구현

## 📝  todo
- [x] 개별 카테고리를 수정하는 뷰의 UI 구성하기 
- [x] 아이콘 토글 기능 구현하기 
- [x] 텍스트 편집 시작할 때 텍스트 색상 변경
