### ISSUE TITLE
[FEAT] EditCategoryView 기능 구현

### ISSUE THREAD

**Issue by Suyeon9911** [TeamHavit/Havit-iOS#65]
## 💡 Issue

EditCategoryView 기능 구현하기 

## 📝  todo
- [ ] 셀 안에있는 편집 아이콘 선택 시, 그 셀에 해당하는 수정화면으로 이동 
- [ ] 개별 카테고리에 해당하는 카테고리 타이틀, 아이콘 데이터 전달...  
- [ ] 중복 카테고리 검사 기능 구현하기 - 후순위..?
